[project]
name = "timesheet-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas==2.3.1",
    "plotly==6.2.0",
    "rich>=14.1.0",
    "streamlit==1.46.1",
]
